/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskManager {
  export type TaskStruct = {
    title: BytesLike;
    description: BytesLike;
    dueDate: BytesLike;
    priority: BytesLike;
    numericId: BytesLike;
    status: BigNumberish;
  };

  export type TaskStructOutput = [
    title: string,
    description: string,
    dueDate: string,
    priority: string,
    numericId: string,
    status: bigint
  ] & {
    title: string;
    description: string;
    dueDate: string;
    priority: string;
    numericId: string;
    status: bigint;
  };
}

export interface TaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeTask"
      | "confidentialProtocolId"
      | "createTask"
      | "createTaskWithNumbers"
      | "createTaskWithText"
      | "deleteTaskById"
      | "editTask"
      | "finalizeTaskDecryption"
      | "getSharedTaskHandles"
      | "getSharedTasks"
      | "getTaskHandles"
      | "getTaskId"
      | "getTaskIndex"
      | "getTasks"
      | "indexToTaskId"
      | "isTaskDecryptionRequested"
      | "isTaskSharedWith"
      | "owner"
      | "renounceOwnership"
      | "requestSharedTaskDecryptionById"
      | "requestTaskDecryptionById"
      | "setFee"
      | "shareTaskById"
      | "sharedTasks"
      | "taskCreationFee"
      | "taskIdToIndex"
      | "tasks"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionRequested"
      | "OwnershipTransferred"
      | "PublicDecryptionVerified"
      | "TaskCreated"
      | "TaskDecrypted"
      | "TaskShared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTaskWithNumbers",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTaskWithText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteTaskById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "editTask",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTaskDecryption",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharedTaskHandles",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharedTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskHandles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskId",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "indexToTaskId",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTaskDecryptionRequested",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTaskSharedWith",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSharedTaskDecryptionById",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTaskDecryptionById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareTaskById",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharedTasks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskCreationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskIdToIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tasks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTaskWithNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTaskWithText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteTaskById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "editTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTaskDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharedTaskHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharedTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTaskId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "indexToTaskId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTaskDecryptionRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTaskSharedWith",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSharedTaskDecryptionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTaskDecryptionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shareTaskById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharedTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskIdToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [taskId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [taskId: bigint, owner: string];
  export interface OutputObject {
    taskId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [owner: AddressLike, taskId: BigNumberish];
  export type OutputTuple = [owner: string, taskId: bigint];
  export interface OutputObject {
    owner: string;
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDecryptedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    user: AddressLike,
    title: BigNumberish,
    dueDate: BigNumberish,
    priority: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    user: string,
    title: bigint,
    dueDate: bigint,
    priority: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    user: string;
    title: bigint;
    dueDate: bigint;
    priority: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSharedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    owner: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [taskId: bigint, owner: string, recipient: string];
  export interface OutputObject {
    taskId: bigint;
    owner: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): TaskManager;
  waitForDeployment(): Promise<this>;

  interface: TaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeTask: TypedContractMethod<
    [taskIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createTask: TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;

  createTaskWithNumbers: TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      encryptedNumericId: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;

  createTaskWithText: TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDescription: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;

  deleteTaskById: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  editTask: TypedContractMethod<
    [
      taskIndex: BigNumberish,
      newEncryptedTitle: BytesLike,
      newEncryptedDueDate: BytesLike,
      newEncryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  finalizeTaskDecryption: TypedContractMethod<
    [
      taskId: BigNumberish,
      clearTitle: BigNumberish,
      clearDueDate: BigNumberish,
      clearPriority: BigNumberish,
      clearDescription: BigNumberish,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getSharedTaskHandles: TypedContractMethod<
    [taskId: BigNumberish, originalOwner: AddressLike],
    [[string, string, string, string]],
    "view"
  >;

  getSharedTasks: TypedContractMethod<
    [recipient: AddressLike],
    [bigint[]],
    "view"
  >;

  getTaskHandles: TypedContractMethod<
    [taskId: BigNumberish],
    [[string, string, string, string]],
    "view"
  >;

  getTaskId: TypedContractMethod<
    [owner_: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  getTaskIndex: TypedContractMethod<
    [owner_: AddressLike, taskId: BigNumberish],
    [bigint],
    "view"
  >;

  getTasks: TypedContractMethod<
    [user: AddressLike],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;

  indexToTaskId: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  isTaskDecryptionRequested: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  isTaskSharedWith: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestSharedTaskDecryptionById: TypedContractMethod<
    [taskId: BigNumberish, originalOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  requestTaskDecryptionById: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  shareTaskById: TypedContractMethod<
    [taskId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  sharedTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  taskCreationFee: TypedContractMethod<[], [bigint], "view">;

  taskIdToIndex: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        title: string;
        description: string;
        dueDate: string;
        priority: string;
        numericId: string;
        status: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<[taskIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTaskWithNumbers"
  ): TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      encryptedNumericId: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTaskWithText"
  ): TypedContractMethod<
    [
      encryptedTitle: BytesLike,
      encryptedDescription: BytesLike,
      encryptedDueDate: BytesLike,
      encryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deleteTaskById"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "editTask"
  ): TypedContractMethod<
    [
      taskIndex: BigNumberish,
      newEncryptedTitle: BytesLike,
      newEncryptedDueDate: BytesLike,
      newEncryptedPriority: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeTaskDecryption"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      clearTitle: BigNumberish,
      clearDueDate: BigNumberish,
      clearPriority: BigNumberish,
      clearDescription: BigNumberish,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSharedTaskHandles"
  ): TypedContractMethod<
    [taskId: BigNumberish, originalOwner: AddressLike],
    [[string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSharedTasks"
  ): TypedContractMethod<[recipient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTaskHandles"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [[string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskId"
  ): TypedContractMethod<
    [owner_: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskIndex"
  ): TypedContractMethod<
    [owner_: AddressLike, taskId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasks"
  ): TypedContractMethod<
    [user: AddressLike],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "indexToTaskId"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTaskDecryptionRequested"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTaskSharedWith"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestSharedTaskDecryptionById"
  ): TypedContractMethod<
    [taskId: BigNumberish, originalOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestTaskDecryptionById"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shareTaskById"
  ): TypedContractMethod<
    [taskId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sharedTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "taskCreationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "taskIdToIndex"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        title: string;
        description: string;
        dueDate: string;
        priority: string;
        numericId: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDecrypted"
  ): TypedContractEvent<
    TaskDecryptedEvent.InputTuple,
    TaskDecryptedEvent.OutputTuple,
    TaskDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "TaskShared"
  ): TypedContractEvent<
    TaskSharedEvent.InputTuple,
    TaskSharedEvent.OutputTuple,
    TaskSharedEvent.OutputObject
  >;

  filters: {
    "DecryptionRequested(uint256,address)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "TaskCreated(address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDecrypted(uint256,address,uint64,uint64,uint8)": TypedContractEvent<
      TaskDecryptedEvent.InputTuple,
      TaskDecryptedEvent.OutputTuple,
      TaskDecryptedEvent.OutputObject
    >;
    TaskDecrypted: TypedContractEvent<
      TaskDecryptedEvent.InputTuple,
      TaskDecryptedEvent.OutputTuple,
      TaskDecryptedEvent.OutputObject
    >;

    "TaskShared(uint256,address,address)": TypedContractEvent<
      TaskSharedEvent.InputTuple,
      TaskSharedEvent.OutputTuple,
      TaskSharedEvent.OutputObject
    >;
    TaskShared: TypedContractEvent<
      TaskSharedEvent.InputTuple,
      TaskSharedEvent.OutputTuple,
      TaskSharedEvent.OutputObject
    >;
  };
}
